-- AlterTable
ALTER TABLE "platform_settings" ALTER COLUMN "freeMaxFileSize" SET DEFAULT 0.2,
ALTER COLUMN "freeMaxFileSize" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "freeMaxStorage" SET DEFAULT 10,
ALTER COLUMN "freeMaxStorage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "proMaxFileSize" SET DEFAULT 2,
ALTER COLUMN "proMaxFileSize" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "proMaxStorage" SET DEFAULT 100,
ALTER COLUMN "proMaxStorage" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "storageUsed" SET DEFAULT 0,
ALTER COLUMN "storageUsed" SET DATA TYPE DOUBLE PRECISION;
